### PR TITLE
Fixing issues with arguments passed to phantomjs

### PR DESCRIPTION
**Pull request by estliberitas**
I fixed following issues connected with phantomjs arguments:
- there were `--undefined=value`
- fixed order of arguments: phantomjs args should be set before script name.

### CODE REVIEW

**Comment by estliberitas** [comment]
lol, this is a dup of #29

**Comment by estliberitas** [comment]
Umm, please have a look [here](https://github.com/sheebz/phantom-proxy/blob/master/lib/proxy.js#L22). After multiple merges right now it seems that we have neither my fixes nor fixes from #29. So, please choose which one you find more good and maybe manually add to lib/proxy.js :)

**Comment by sheebz** [comment]
yes, trying to clean up now.

**Comment by sheebz** [comment]
Doh!  Yeah, looks like your changes got clobbered.  I think the options changes you made should be in there now.  Can you take a look?

**Comment by estliberitas** [comment]
Seems ok now, will check how it works tomorrow - already in the bed,
bye-bye. :)

**Pull request merged**
