### PR TITLE
Fixing issues caused by callbacks for page.open and page.includeJs

### PR DESCRIPTION
**Pull request by estliberitas**
This pull request simply solves problem with page#open() and page#includeJs(), which were mentioned in #9.

### CODE REVIEW

**Comment by estliberitas** [comment]
Also added "event-stream" as dependency to package.json because it's require()-d but not fetched by `npm install phantom-proxy`

**Comment by estliberitas** [comment]
Ping @sheebz :)

**Comment by sheebz** [comment]
merged and published to npm.  Thanks for the help.

**Comment by AndrewRayCode** [comment]
fyi I got this as well recently

Error: cannot access member `statusCode' of deleted QObject, /usr/local/lib/node_modules/phantom-proxy/lib/server/webpage.js, 179

for me 179 is the last line of this block:

```
    open:function (url) {
        var self = this;
        var called = false;
        try {
            this.page.open.call(self.page, url, function (status) {
                if (called) {
                    return;
                }
                called = true;
                if (status === "success") {
                    self.response.statusCode = 200;
```

does not seem to be consistently reproducible :(

**Comment by AndrewRayCode** [comment]
I have also gotten:

Error: cannot call function of deleted QObject, :/modules/webpage.js, 377

Even though there is no modules folder?? Maybe that's from inside phantom?

can we reopen this?

**Comment by popovicititus** [comment]
I'm also getting this:

cannot access member `statusCode' of deleted QObject

  scaperServer.js:37
  :/modules/webpage.js:337

after page.open() is called twice on the same page.

**Pull request merged**
